# Generated by Django 4.0.1 on 2022-01-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='trx_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=50, verbose_name='Transaction Type'),
        ),
    ]
